### ISSUE TITLE
class MontyHallSimulator 생성

### ISSUE THREAD

**Issue by miso2203** [team-no-1-fizzbuzz/MontyHallSimulation#2]
## Description

시뮬레이션을 실행하고 두가지 전략에 대한 승률을 계산합니다.

## Tasks

- [ ] MontyHallSimulator 생성자 정의
- [ ] simulate 게임 전략 함수 정의
- [ ] get_results 승률계산 함수 정의
